# Generated by Django 3.2.5 on 2021-07-17 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('deskripsi', models.TextField(blank=True, null=True)),
                ('value1', models.FloatField(blank=True, null=True)),
                ('value2', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='JenisPenyakit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('deskripsi', models.TextField(blank=True, null=True)),
                ('value1', models.FloatField(blank=True, null=True)),
                ('value2', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Solusi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('deskripsi', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
