# Generated by Django 3.2.5 on 2021-07-24 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_cabai', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cfpakar',
            name='hama',
        ),
        migrations.AddField(
            model_name='cfpakar',
            name='hama',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_cabai.hama'),
        ),
        migrations.RemoveField(
            model_name='cfpakar',
            name='jenis_penyakit',
        ),
        migrations.AddField(
            model_name='cfpakar',
            name='jenis_penyakit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_cabai.jenispenyakit'),
        ),
        migrations.RemoveField(
            model_name='cfpengguna',
            name='hama',
        ),
        migrations.AddField(
            model_name='cfpengguna',
            name='hama',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_cabai.hama'),
        ),
        migrations.RemoveField(
            model_name='cfpengguna',
            name='nama_masalah',
        ),
        migrations.AddField(
            model_name='cfpengguna',
            name='nama_masalah',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_cabai.permasalahan'),
        ),
    ]
