# Generated by Django 3.2.5 on 2021-07-17 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cabai', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permasalahan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_masalah', models.CharField(max_length=100)),
                ('penjelasan', models.TextField(blank=True, null=True)),
                ('hama', models.ManyToManyField(to='app_cabai.Hama')),
                ('jenis_penyakit', models.ManyToManyField(blank=True, null=True, to='app_cabai.JenisPenyakit')),
                ('solusi', models.ManyToManyField(blank=True, null=True, to='app_cabai.Solusi')),
            ],
        ),
    ]
