# Generated by Django 3.2.5 on 2021-07-24 09:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cabai', '0002_auto_20210724_0516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cfpengguna',
            name='value',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-1.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
    ]
