# Generated by Django 3.2.5 on 2021-07-24 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cabai', '0003_alter_cfpengguna_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='jenispenyakit',
            name='solusi',
            field=models.ManyToManyField(blank=True, null=True, to='app_cabai.Solusi'),
        ),
    ]
